version: "3.8"

networks:
  store_network:

services:
  store-web-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - store-api
    networks:
      - store_network

  store-api:
    build:
      context: ./backend
      dockerfile: ./src/Store.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - store-postgres
    networks:
      - store_network
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=store-postgres;Port=5432;Database=store;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80

  store-postgres:
    image: postgres:latest
    container_name: store-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=store
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - store_network
