version: "3.8"

networks:
  store_network:

services:
  store-web-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - store-api
    networks:
      - store_network

  store-api:
    build:
      context: ./backend
      dockerfile: ./src/Store.API/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - store-postgres
    networks:
      - store_network
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  store-postgres:
    image: postgres:15.3-alpine
    container_name: store-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - store_network

  store-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: store-pgadmin
    restart: always
    depends_on:
      - store-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - store_network
